name: Dockerhub Build CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Code Checkout
        uses: actions/checkout@v2
      # Install Docker
      - name: Set up docker build
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      # Builds java-based gradle project      
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2.1.4
        with:
          build-root-directory: devopsguru_eks_test
          gradle-version: 8.1.1
          arguments: build
      # Build and push Docker image
      - name: Build Docker Image, but no push
        uses: docker/build-push-action@v2.10.0
        with:
          context: devopsguru_eks_test
          tags: amazon/aws-devopsguru-eks-test-harness-test-service:latest
